spring:
    datasource:
        url: jdbc:mysql://172.0.0.1/user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        driver-class-name: com.mysql.jdbc.Driver


#    # redis生产环境
#    redis:
#        host: 172.19.197.249
#        port: 6379
#        password: zhangdan@91


# swagger开关 true/false
swagger:
    enable: false

